[package]
name = "levenberg-marquardt"
version = "0.5.2"
authors = ["Jannik Schürg <schuerg@ins.uni-bonn.de>", "Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"
description = "Levenberg-Marquardt algorithm built on top of nalgebra"
keywords = ["optimization", "optimizer", "levenberg", "marquardt", "squares"]
categories = ["algorithms", "computer-vision", "science::robotics", "no-std", "mathematics"]
repository = "https://github.com/rust-cv/levenberg-marquardt"
documentation = "https://docs.rs/levenberg-marquardt/"
license = "MIT"
readme = "README.md"

[features]
default = []
minpack-compat = []

[dependencies]
nalgebra = { version = "0.22.0", default-features = false }
num-traits = { version = "0.2.12", default-features = false }
cfg-if = "0.1.10"

[dev-dependencies]
arrsac = "0.5.0"
rand = { version = "0.7.3", default-features = false }
nalgebra = "0.22.0"
pcg_rand = "0.11.1"
sample-consensus = "1.0.1"
approx = "0.3.2"

[build-dependencies]
rustc_version = "0.2.3"

[profile.test]
# The line fitting test case needs this to run in reasonable amount of time
opt-level = 2

[package.metadata.docs.rs]
# To build locally use
#   RUSTDOCFLAGS="--html-in-header katex-header.html" cargo doc --no-deps --document-private-items --open
rustdoc-args = [ "--html-in-header", "katex-header.html" ]
