[package]
name = "levenberg-marquardt"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = { version = "0.19.0", default-features = false }
alga = "0.9.2"
num-traits = "0.2.10"
